name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Deploy
      uses: solybum/hexo-deploy@master
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_REPOSITORY: wangyang1749/myblog # The repository the action should deploy to.
        BRANCH: gh-pages  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.
